// Code generated by "enumer -type=ExchangeID"; DO NOT EDIT

package models

import (
	"fmt"
)

const _ExchangeID_name = "BitflyerPoloniexHitbtcUnknownExchange"

var _ExchangeID_index = [...]uint8{0, 8, 16, 22, 37}

func (i ExchangeID) String() string {
	i -= 1
	if i < 0 || i >= ExchangeID(len(_ExchangeID_index)-1) {
		return fmt.Sprintf("ExchangeID(%d)", i+1)
	}
	return _ExchangeID_name[_ExchangeID_index[i]:_ExchangeID_index[i+1]]
}

var _ExchangeIDNameToValue_map = map[string]ExchangeID{
	_ExchangeID_name[0:8]:   1,
	_ExchangeID_name[8:16]:  2,
	_ExchangeID_name[16:22]: 3,
	_ExchangeID_name[22:37]: 4,
}

func ExchangeIDString(s string) (ExchangeID, error) {
	if val, ok := _ExchangeIDNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExchangeID values", s)
}
